/******************************************************************
 * File: source//script_token.cpp
 *
 * This file was automatically generated by CppCC Version 0.0.6
 * DO NOT EDIT MANUALLY
 ******************************************************************/


#include "script_token.h"


const int script_tut::scriptToken::eof = 0;
const int script_tut::scriptToken::ws = 1;
const int script_tut::scriptToken::SHORT_COMMENT = 2;
const int script_tut::scriptToken::eol = 3;
const int script_tut::scriptToken::IF = 4;
const int script_tut::scriptToken::ELSE = 5;
const int script_tut::scriptToken::L_PAR = 6;
const int script_tut::scriptToken::R_PAR = 7;
const int script_tut::scriptToken::L_CURLY = 8;
const int script_tut::scriptToken::R_CURLY = 9;
const int script_tut::scriptToken::COMMA = 10;
const int script_tut::scriptToken::SEMICOLON = 11;
const int script_tut::scriptToken::ASSIGN = 12;
const int script_tut::scriptToken::EQUAL = 13;
const int script_tut::scriptToken::NEQUAL = 14;
const int script_tut::scriptToken::ADD = 15;
const int script_tut::scriptToken::SUB = 16;
const int script_tut::scriptToken::MULT = 17;
const int script_tut::scriptToken::DIV = 18;
const int script_tut::scriptToken::CONCAT = 19;
const int script_tut::scriptToken::LOGIC_OR = 20;
const int script_tut::scriptToken::LOGIC_AND = 21;
const int script_tut::scriptToken::IDENTIFIER = 22;
const int script_tut::scriptToken::VAR_NAME = 23;
const int script_tut::scriptToken::DECIMAL = 24;
const int script_tut::scriptToken::STRING = 25;



/* End of file. */
